### ISSUE TITLE
Addon doesn't appear in Blender 2.90 search 

### ISSUE THREAD

**Issue by jonmatthis** [AlansCodeLog/blender-debugger-for-vscode#22] opened 2020-11-18 18:05 UTC
It works in 2.83, but in 2.9 when I search for "Debug" the addon does not appear 

OS:

Add-on Version: 1.0.0

Blender Version: 2.90

VS Code Version: ?

VS Code Python Extension Version:

PTVSD Version:

Paths listed by `where python` or the corresponding command:

Does VS Code / Visual Studio connect to the troubleshooting script?

Python path/interpreter detected/selected by VS Code/Visual Studio:

**Comment by alanscodelog** [comment] 2020-11-19 20:32
Duplicate of #18. See it for solution.

**Closed as completed by alanscodelog** 2020-11-19 20:32 UTC
